<div id="page">  
    <div id="hlegal"><?php echo $this->tit; ?></div>  
    <div id="publicidad"> 		
        <img width="100%" src="<?php echo MEDIA_URL ?>img/nextel/banner-nextel-tonos.jpg">
    </div>  
    <?php if ($saldo == "no") { ?>
        <div id="list-titulo-precio">      
            <div>
            <?php } ?>
            <div id="list-titulo-precio">      
                <p><b>Gracias por suscribirte, para poder cancelar la suscripci&oacute;n envia SALIR al 4556</b></p>
                <div class="btn-ancho" style="text-align: center;color: #FFFFFF;font-weight: bold;margin: 20px auto;border-radius: 4px;padding: 3px;-moz-box-sizing: border-box;border: medium none;" >
                    <a href="http://174.121.234.90/nxpe/Baja.aspx?id=<?php echo $this->iden ?>" style="color: #FFFFFF; font-size: 14px;background-color:#E05206;font-weight:bold;">Click Aqu&iacute; para descargar el contenido seleccionado</a>
                </div>
                <div class="btn-ancho" style="text-align: center;color: #FFFFFF;font-weight: bold;margin: 20px auto;border-radius: 4px;padding: 3px;-moz-box-sizing: border-box;border: medium none;" >
                    <a href="/#tn" style="color: #FFFFFF; font-size: 14px;background-color:#E05206;font-weight:bold;">
                        Regresar</a>
                </div>
            </div>  
        </div>
    </div> 
</div>